# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  enable-experiment:
    - spread-collections
    - control-flow-collections

linter:
  rules:
    lines_longer_than_80_chars: false